apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: gw-proxy
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: gateway
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  containers:
    - env:
        - name: KONG_ANONYMOUS_REPORTS
          value: 'off'
        - name: KONG_ADMIN_LISTEN
          value: '0.0.0.0:8001, 0.0.0.0:8444 ssl'
        - name: KONG_DATABASE
          value: 'off'
        - name: KONG_PROXY_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_ADMIN_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_PROXY_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_ERROR_LOG
          value: /dev/stderr
        - name: KONG_TRUSTED_IPS
          value: 0.0.0.0/0
        - name: KONG_REAL_IP_RECURSIVE
          value: 'off'
        - name: KONG_NGINX_LARGE_CLIENT_HEADER_BUFFERS
          value: 4 64K
        - name: KONG_HEADERS
          value: 'off'
        - name: KONG_PROXY_LISTEN
          value: '0.0.0.0:8000, 0.0.0.0:8443 http2 ssl'
        - name: KONG_REAL_IP_HEADER
          value: X-Real-IP
        - name: KONG_PLUGINS
          value: 'gwa-ip-anonymity'
        - name: KONG_DECLARATIVE_CONFIG
          value: /conf/kong.yaml
      image: 'docker-registry.default.svc:5000/dbc-konga-tools/kong-gwa:1.1.2'
      imagePullPolicy: Always
      name: gateway
      ports:
        - containerPort: 8001
          name: admin
          protocol: TCP
        - containerPort: 8000
          name: proxy
          protocol: TCP
        - containerPort: 8443
          name: proxy-ssl
          protocol: TCP
        - containerPort: 8444
          name: admin-ssl
          protocol: TCP
      volumeMounts:
        - mountPath: /usr/local/kong
          name: kong-run
        - mountPath: /conf
          name: kong-conf
    - name: httpie
      command:
        - tail
        - -f
        - /dev/null
      image: alpine/httpie
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /.httpie
          name: httpie-run
  volumes:
    - emptyDir: {}
      name: kong-run
    - emptyDir: {}
      name: httpie-run
    - configMap:
        defaultMode: 420
        items:
          - key: kong.yaml
            path: kong.yaml
        name: gwa-demo-config
      name: kong-conf
---
apiVersion: v1
data:
  kong.yaml: |-
    _format_version: "1.1"

    services:
    - name: gwa-demo-service
      url: "http://httpbin.org"
      routes:
      - name: gwa-demo
        paths:
        - /

    routes:
    - name: gwa-demo
      service: gwa-demo-service
      hosts: ["gwa-demo.pathfinder.gov.bc.ca"]
      plugins:
      - name: gwa-ip-anonymity
      - name: rate-limiting

    plugins:
    - name: gwa-ip-anonymity
      service: gwa-demo-service
      config:
        ipv4_mask: 0
        ipv6_mask: 0       
    - name: rate-limiting
      route: gwa-demo
      config:
        second: 1
        minute: 10      
kind: ConfigMap
metadata:
  name: gwa-demo-config
