apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: kong-rhel-minimal
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/dbc-oem-tools/kong-rhel-minimal
    name: latest
status:
  dockerImageRepository: ""
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: kong-rhel-minimal
  name: kong-rhel-minimal
spec:
  output:
    to:
      kind: ImageStreamTag
      name: kong-rhel-minimal:latest
  source:
    dockerfile: |-
      FROM registry.access.redhat.com/ubi8-minimal
      MAINTAINER leo.lou@gov.bc.ca

      LABEL name="Kong" \
            vendor="Kong" \
            version="${KONG_VERSION}" \
            release="1" \
            url="https://konghq.com" \
            summary="Next-Generation API Platform for Modern Architectures" \
            description="Next-Generation API Platform for Modern Architectures"

      RUN microdnf install --nodocs wget && \
          wget https://bintray.com/kong/kong-rpm/rpm -O bintray-kong-kong-rpm.repo && \
          sed -i -e 's/baseurl.*/&\/rhel\/7'/ bintray-kong-kong-rpm.repo && \
          mv bintray-kong-kong-rpm.repo /etc/yum.repos.d/ && microdnf --enablerepo=bintray--kong-kong-rpm update && \
          microdnf --enablerepo=bintray--kong-kong-rpm install --nodocs kong libyaml && \
          # OpenShift specific. OpenShift runs containers using an arbitrarily assigned user ID.
          # This user doesn't have access to change file permissions during runtime, they have to be changed during image building.
          # https://docs.okd.io/latest/creating_images/guidelines.html#use-uid
          mkdir -p "/usr/local/kong" && \
          chgrp -R 0 "/usr/local/kong" && \
          chmod -R g=u "/usr/local/kong" && \
          wget -O /LICENSE "https://raw.githubusercontent.com/Kong/kong/master/LICENSE" && \
          wget -O /runme "https://raw.githubusercontent.com/Kong/docker-kong/${KONG_VERSION}/rhel/docker-entrypoint.sh" && \
          chmod 755 /runme && \
          microdnf remove wget && microdnf clean all && \
          rm -rf /tmp/*

      ENTRYPOINT ["/runme"]
      VOLUME /usr/local/kong
      EXPOSE 8000 8443 8001 8444
      STOPSIGNAL SIGTERM
      CMD ["kong", "docker-start"]
    type: Dockerfile
  strategy:
    dockerStrategy:
      env:
        - name: KONG_VERSION
          value: '1.1.2'
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8-minimal
    type: Docker
